name: Sync_CI_Repo

on: pull_request_target

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.LTX_SIMULATION_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request?.number ?? context.payload.number;

            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            const org = 'Modelica'
            const author = context.payload.pull_request.user.login

            const members = await github.paginate(
            github.rest.orgs.listMembers,
              { org, per_page: 100 }
            )
            core.info(`Author: ${author}`)
            core.info(`Members:`)
            for (const member of members) {
              core.info(`- ${member.login}`)
            }
            const isMember = members.some(m => m.login === author)

            const labels = (pr.labels || []).map(l => typeof l === 'string' ? l : l.name);
            const hasLabel = labels.includes('approved_for_ci');

            await github.rest.repos.createDispatchEvent({
              owner: '${{ secrets.PRIVATE_CI_OWNER }}',
              repo: '${{ secrets.PRIVATE_CI_REPO }}',
              event_type: 'CI_trigger_type',
              client_payload: {
                number: prNumber,
                head_sha: pr.head.sha,
                base_sha: pr.base.sha,
                has_label: hasLabel,
                is_member: isMember,
                github_repo: context.repo.full_name
              }
            });
